services:
    db-mongo:
        container_name: db-mongo
        image: mongo:6.0.5-jammy
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - mongodata:/data/db
        restart: on-failure
    node-app:
        container_name: node-app
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: development
        # RUN in debug mode: npm run start:debug --> Also start your debugger
        # Run in dev mode: npm run start:dev
        command: npm run start:debug
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - .env
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${DEBUG_PORT}:${DEBUG_PORT}
        depends_on:
            - db-mongo
        restart: on-failure

volumes:
    mongodata:
        driver: local
    node-app:
